version: '3'

services:
  nginx:
    image: docker.io/library/astro-ui
    # stdin_open: true # docker run -i
    # tty: true        # docker run -t
    restart: unless-stopped
    ports:
      - 80:8080
      - 443:443    